### ISSUE TITLE
Phaseshift

### ISSUE THREAD

**Issue by classic-audio** [yellobyte/DacESP32#5]
Would it be possible to add more phaseshift?

I would like to have phaseshift like:  30dg  60 dg   90dg

**Comment by yellobyte** [comment]
Unfortunately this option is not supported by ESP32 SoC as stated in the specification:  

![CW_phaseshift](https://github.com/yellobyte/DacESP32/assets/76921504/7ac79a64-a7ac-4526-98dd-38e6f1d68429)
